source 'https://github.com/CocoaPods/Specs.git'

target 'RxApollo_Tests' do
	
	platform :ios, '9.0'
	
	# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
	use_frameworks!
	inhibit_all_warnings!
	
  pod 'RxApollo', :path => '../'
  
end
